### ISSUE TITLE
High number of dependencies

### ISSUE THREAD

**Issue by Xwilarg** [top-gg/dotnet-sdk#17]
Hi,

So I wanted to use this library for one of my project but there is an inside number of dependencies and I don't understand why they are here:
![image](https://user-images.githubusercontent.com/20053454/94139926-bf700700-fe6a-11ea-9c2a-1765517f8934.png)

I'm not sure where they are coming from but looking at the csproj there should only be a dependency to Newtonsoft.Json

**Comment by Xwilarg** [comment]
After looking for a bit I found that:
https://stackoverflow.com/questions/47365136/why-does-my-net-standard-nuget-package-trigger-so-many-dependencies/47366401#47366401

So updating the library to .NET Standard 2.0 should solve the issue

**Comment by Faith1sGay** [comment]
This was solved by updating the package to Net 5. 


I've been told that this shouldn't break any net core bots but if it does, please let me know.
