### ISSUE TITLE
v1.4.5 GetVotersAsync method returns all user Ids as 0

### ISSUE THREAD

**Issue by ta1H3n** [top-gg/dotnet-sdk#20]
Issue as per title. 

Works perfectly in v1.4.0

**Comment by Faith1sGay** [comment]
huh, that's weird. I just double checked and I didn't even change anything on that method at all, other than codemaid changing whitespacing, it should be fine. 
Could I see some screenshots or something, so I can get more information?

**Comment by Faith1sGay** [comment]
It just came to my mind that it might be an issue with `System.Text.Json`, ill double check it when I get a chance.

**Comment by Faith1sGay** [comment]
I think i found the issue and I'll roll out a fix for it later today / tomorrow / this weekend.

**Comment by Faith1sGay** [comment]
I think I might've fixed it, I'll leave the issue open in case I didn't.

**Comment by velddev** [comment]
Could you write a test with the setup System.Text.Json formatter?
